logdir_path: '/content/drive/My Drive/pyvc/train1/logdir'
log_step: 1
num_workers: 16
max_len: 2000

---
default:
    sr: 22050
    win_length: 1024
    hop_length: 256
    n_fft: 1024
    preemphasis: 0.97
    n_mfcc: 40
    n_iter: 60 # Number of inversion iterations
    n_mels: 80
    duration: 2
    max_db: 35
    min_db: -55
    quantize_db: 101

    # model
    hidden_units: 256  # alias: E
    num_banks: 16
    num_highway_blocks: 4
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    t: 1.0  # temperature
    dropout_rate: 0.2

    # train
    batch_size: 32

    # train test split
    data_split: 1.0
---
train:
    # path
    data_path: '/content/drive/My Drive/timit/data/TRAIN/DR8/*/*.wav'
    # model
    hidden_units: 256  # alias: E
    num_banks: 16
    num_highway_blocks: 4
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    t: 1.0  # temperature
    dropout_rate: 0.2

    # train
    batch_size: 32
    lr: 0.001
    num_epochs: 1000
    save_per_epoch: 2
---
test:
    # path
    data_path: '/content/drive/My Drive/timit/data/TEST/DR8/F*/*.wav'

    # test
    batch_size: 2

    # data loader test data path 1
    test_data_path1: '/data/public/rw/datasets/voice_all/timit/TIMIT/TRAIN/DR5/FDMY0/SA1.wav'